<?php

namespace Container671tVoD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBooksImporterCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\BooksImporterCommand' shared autowired service.
     *
     * @return \App\Command\BooksImporterCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'BooksImporterCommand.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CsvFileReader.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'BookImporterService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Utils'.\DIRECTORY_SEPARATOR.'ImporterUtils.php';

        $a = ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'));
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        $container->privates['App\\Command\\BooksImporterCommand'] = $instance = new \App\Command\BooksImporterCommand($a, new \App\Service\CsvFileReader(), new \App\Service\BookImporterService($b, $a, new \App\Utils\ImporterUtils($b)));

        $instance->setName('app:book_importer');
        $instance->setAliases(['app:add-books']);
        $instance->setDescription('Update books database.');

        return $instance;
    }
}
