<?php

namespace ContainerBP8EUxw;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBooksImporterCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\Books_Importer_command' shared autowired service.
     *
     * @return \App\Command\Books_Importer_command
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Books_Importer_command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CsvFileReader.php';

        $container->privates['App\\Command\\Books_Importer_command'] = $instance = new \App\Command\Books_Importer_command(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), new \App\Service\CsvFileReader());

        $instance->setName('app:book_importer');
        $instance->setAliases(['app:add-books']);
        $instance->setDescription('Update books database.');

        return $instance;
    }
}
