<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBkoHDIT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBkoHDIT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBkoHDIT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBkoHDIT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBkoHDIT\App_KernelDevDebugContainer([
    'container.build_hash' => 'BkoHDIT',
    'container.build_id' => '27bc11d6',
    'container.build_time' => 1713447493,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBkoHDIT');
