<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9t7KfKp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9t7KfKp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9t7KfKp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9t7KfKp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9t7KfKp\App_KernelDevDebugContainer([
    'container.build_hash' => '9t7KfKp',
    'container.build_id' => 'e6034f94',
    'container.build_time' => 1713196631,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container9t7KfKp');
