<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBP8EUxw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBP8EUxw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBP8EUxw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBP8EUxw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBP8EUxw\App_KernelDevDebugContainer([
    'container.build_hash' => 'BP8EUxw',
    'container.build_id' => '446aee1b',
    'container.build_time' => 1713557247,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBP8EUxw');
