<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_book' => [[], ['_controller' => 'App\\Controller\\FetchEntityController::fetchBooks'], [], [['text', '/books']], [], [], []],
    'app_authors' => [[], ['_controller' => 'App\\Controller\\FetchEntityController::fetchAuthors'], [], [['text', '/authors']], [], [], []],
    'app_publishers' => [[], ['_controller' => 'App\\Controller\\FetchEntityController::fetchPublishers'], [], [['text', '/publishers']], [], [], []],
    'App\Controller\FetchEntityController::fetchBooks' => [[], ['_controller' => 'App\\Controller\\FetchEntityController::fetchBooks'], [], [['text', '/books']], [], [], []],
    'App\Controller\FetchEntityController::fetchAuthors' => [[], ['_controller' => 'App\\Controller\\FetchEntityController::fetchAuthors'], [], [['text', '/authors']], [], [], []],
    'App\Controller\FetchEntityController::fetchPublishers' => [[], ['_controller' => 'App\\Controller\\FetchEntityController::fetchPublishers'], [], [['text', '/publishers']], [], [], []],
];
