<?php

namespace ContainerQ9bfCwU;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MZkpFl8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mZkpFl8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mZkpFl8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bookService' => ['privates', '.errored.WgGf7Xs', NULL, 'Cannot determine controller argument for "App\\Controller\\BookController::createBook()": the $bookService argument is type-hinted with the non-existent class or interface: "App\\Service\\BookService".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'bookService' => '?',
            'entityManager' => '?',
        ]);
    }
}
