<?php

namespace ContainerQ9bfCwU;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_WgGf7XsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.WgGf7Xs' shared service.
     *
     * @return \App\Service\BookService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\BookController::createBook()": the $bookService argument is type-hinted with the non-existent class or interface: "App\\Service\\BookService".');
    }
}
